services:

  frontend:
    container_name: smartweld-frontend

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3001:3000"

    depends_on:
      - backend

    restart: always

  backend:
    container_name: smartweld-backend

    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "8001:8000"

    environment:
      DATABASE_URL: postgresql://postgres:vassu@db:5432/Smart_Weld

    depends_on:
      - db

    restart: always

  db:
    container_name: smartweld-db

    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vassu
      POSTGRES_DB: Smart_Weld

    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: always

volumes:
  postgres-data:
