version: "3.8"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: vassu
      POSTGRES_DB: smartweld
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
    depends_on:
      - postgres

  frontend:
    build: .
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
