/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303032",
        "inverse-on-surface": "#f2f0f2",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-container": "#76849f",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#b8c8da",
        "primary": "#000000",
        "outline-variant": "#c5c6cd",
        "surface-container-low": "#f5f3f5",
        "on-secondary-container": "#556474",
        "primary-fixed-dim": "#b9c7e4",
        "error": "#ba1a1a",
        "on-surface": "#1b1b1d",
        "surface-dim": "#dbd9db",
        "on-background": "#1b1b1d",
        "on-tertiary-fixed": "#2b1701",
        "on-secondary-fixed-variant": "#394857",
        "outline": "#75777e",
        "background": "#fbf9fb",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#9f7d5b",
        "tertiary": "#000000",
        "on-tertiary-fixed-variant": "#5d4124",
        "surface-tint": "#515f78",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#44474d",
        "tertiary-fixed": "#ffdcbd",
        "tertiary-fixed-dim": "#e7bf99",
        "primary-container": "#0d1c32",
        "on-primary-fixed": "#0d1c32",
        "secondary": "#50606f",
        "surface-container-highest": "#e4e2e4",
        "secondary-fixed": "#d4e4f6",
        "surface": "#fbf9fb",
        "on-primary-fixed-variant": "#39475f",
        "surface-container": "#efedef",
        "on-secondary-fixed": "#0d1d2a",
        "secondary-container": "#d1e1f4",
        "surface-container-high": "#eae7ea",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4e2e4",
        "surface-bright": "#fbf9fb",
        "tertiary-container": "#2b1701",
        "on-error": "#ffffff",
        "inverse-primary": "#b9c7e4",
        "safety-orange": "#FF5F00",
        "industrial-blue": "#0D1C32"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "48px",
        "gutter": "20px",
        "xl": "80px",
        "md": "24px",
        "base": "8px",
        "xs": "4px",
        "margin-mobile": "16px",
        "sm": "12px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "button-text": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "button-text": ["16px", {"lineHeight": "20px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-bold": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}
